/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { DiaryAnchor, DiaryAnchorInterface } from "../DiaryAnchor";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "seasonId",
        type: "string",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "dataHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "anchoredAt",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "anchoredBy",
        type: "address",
      },
    ],
    name: "Anchored",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "seasonId",
        type: "string",
      },
      {
        internalType: "bytes32",
        name: "dataHash",
        type: "bytes32",
      },
    ],
    name: "anchor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610177806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063dbe5174e14610030575b600080fd5b61004361003e366004610090565b610045565b005b336001600160a01b0316817feb1baceb4ca038e38f81b6338a66dd2b970a8071ac3e007a0fabb34fd6aa789a85854260405161008393929190610108565b60405180910390a3505050565b6000806000604084860312156100a557600080fd5b833567ffffffffffffffff808211156100bd57600080fd5b818601915086601f8301126100d157600080fd5b8135818111156100e057600080fd5b8760208285010111156100f257600080fd5b6020928301989097509590910135949350505050565b604081528260408201528284606083013760006060848301015260006060601f19601f860116830101905082602083015294935050505056fea2646970667358221220721fc2134e980cf6d0bb19c73dff84e99a5d6132e0646c98245fa1725beb37c064736f6c63430008140033";

type DiaryAnchorConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DiaryAnchorConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DiaryAnchor__factory extends ContractFactory {
  constructor(...args: DiaryAnchorConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      DiaryAnchor & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): DiaryAnchor__factory {
    return super.connect(runner) as DiaryAnchor__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DiaryAnchorInterface {
    return new Interface(_abi) as DiaryAnchorInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): DiaryAnchor {
    return new Contract(address, _abi, runner) as unknown as DiaryAnchor;
  }
}
