/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DiaryAnchorInterface extends Interface {
  getFunction(nameOrSignature: "anchor"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Anchored"): EventFragment;

  encodeFunctionData(
    functionFragment: "anchor",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "anchor", data: BytesLike): Result;
}

export namespace AnchoredEvent {
  export type InputTuple = [
    seasonId: string,
    dataHash: BytesLike,
    anchoredAt: BigNumberish,
    anchoredBy: AddressLike
  ];
  export type OutputTuple = [
    seasonId: string,
    dataHash: string,
    anchoredAt: bigint,
    anchoredBy: string
  ];
  export interface OutputObject {
    seasonId: string;
    dataHash: string;
    anchoredAt: bigint;
    anchoredBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DiaryAnchor extends BaseContract {
  connect(runner?: ContractRunner | null): DiaryAnchor;
  waitForDeployment(): Promise<this>;

  interface: DiaryAnchorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchor: TypedContractMethod<
    [seasonId: string, dataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchor"
  ): TypedContractMethod<
    [seasonId: string, dataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Anchored"
  ): TypedContractEvent<
    AnchoredEvent.InputTuple,
    AnchoredEvent.OutputTuple,
    AnchoredEvent.OutputObject
  >;

  filters: {
    "Anchored(string,bytes32,uint256,address)": TypedContractEvent<
      AnchoredEvent.InputTuple,
      AnchoredEvent.OutputTuple,
      AnchoredEvent.OutputObject
    >;
    Anchored: TypedContractEvent<
      AnchoredEvent.InputTuple,
      AnchoredEvent.OutputTuple,
      AnchoredEvent.OutputObject
    >;
  };
}
